/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Design;

import Class.DiemHocTap;
import Class.Lop;
import Service.DanhSachLopService;
import Service.QLDSVService;
import Service.SinhVienService;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author hcshl
 */
public class DanhSachLopUI extends javax.swing.JFrame {

    /**
     * Creates new form DanhSachLopUI
     */
    Connection conn ;


	DefaultTableModel dtmSinhVien;
	
	DanhSachLopService lopService ;
	Lop lop;
	ArrayList<Lop> dsLop;
	
	SinhVienService sinhVienService ;
	ArrayList<DiemHocTap> dsSV ;
	DiemHocTap sv ;
	
    
    
    public DanhSachLopUI() {
        
      //  this.rootDSLop = (DefaultMutableTreeNode) treeDSLop.getModel();
        initComponents();
        ketNoiOracle();
        hienThiToanBoLopHocLenCay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void ketNoiOracle() {
		try {
			Class.forName("oracle.jdbc.driver.OracleDriver");
			String strConn="jdbc:oracle:thin:@localhost:1521/orcl";
			conn=DriverManager.getConnection(strConn, "HCS", "son123");
			
		}
		catch(Exception ex)
		{
			ex.printStackTrace();
		}
	}
    
    private void hienThiToanBoLopHocLenCay() {
                DefaultTreeModel model = (DefaultTreeModel) treeDSLop.getModel();
        	DefaultMutableTreeNode rootDSLop =  (DefaultMutableTreeNode) model.getRoot();
		if(lopService == null)
                    lopService=new DanhSachLopService();
                dsLop=lopService.LayDanhSachLop(DangNhapUI.setLayTaiKhoan());
                rootDSLop.removeAllChildren();
  
		for(Lop l: dsLop)
		{
			DefaultMutableTreeNode nodeLop=new DefaultMutableTreeNode(l);
			rootDSLop.add(nodeLop);
		}
		treeDSLop.expandRow(0);
	}
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbSinhVien = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mssv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        hotensv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        diemqt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        diemth = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        diemgk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        diemck = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btUpdate = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        treeDSLop = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý điểm sinh viên");

        tbSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MSSV", "Tên sinh viên", "Điểm quá trình", "Điểm thực hành", "Điểm giữa kỳ", "Điểm cuối kỳ", "Điểm trung bình"
            }
        ));
        tbSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSinhVienMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbSinhVien);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setLayout(new java.awt.GridLayout(6, 2));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MSSV:");
        jPanel1.add(jLabel1);

        mssv.setEditable(false);
        jPanel1.add(mssv);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Họ Tên:");
        jPanel1.add(jLabel2);

        hotensv.setEditable(false);
        jPanel1.add(hotensv);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Điểm QT:");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3);
        jPanel1.add(diemqt);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Điểm TH:");
        jPanel1.add(jLabel6);
        jPanel1.add(diemth);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Điểm GK:");
        jPanel1.add(jLabel5);
        jPanel1.add(diemgk);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Điểm CK:");
        jPanel1.add(jLabel4);
        jPanel1.add(diemck);

        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btUpdate.setText("Cập nhật");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btUpdate);

        btDelete.setText("Xóa");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btDelete);

        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jPanel2.add(jPanel3, "card2");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel5);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Danh sách lớp");
        treeDSLop.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeDSLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeDSLopMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(treeDSLop);

        jSplitPane1.setLeftComponent(jScrollPane3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void treeDSLopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeDSLopMouseClicked
        // TODO add your handling code here:
        dsSV =new ArrayList<DiemHocTap>();
						DefaultMutableTreeNode nodeSelected= (DefaultMutableTreeNode) treeDSLop.getLastSelectedPathComponent();
						if(nodeSelected==null)return;
						if(nodeSelected.getLevel()==0)return;
						if(sinhVienService==null)
							sinhVienService=new SinhVienService();
						lop=(Lop) nodeSelected.getUserObject();
						if(lop!=null)
							dsSV=sinhVienService.layDanhSachSinhVienTheoLop(lop.getMaLop());
						hienThiDanhSachSVLenBangDiem();
    }//GEN-LAST:event_treeDSLopMouseClicked

    private void tbSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSinhVienMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbSinhVien.getModel();
         /*int row=tbSinhVien.getSelectedRow();
				if(row==-1) return;
				sv=dsSV.get(row);

				mssv.setText(sv.getMssv());
				hotensv.setText(sv.getTensv());
				diemqt.setText(sv.getDiemqt()+"");
				diemth.setText(sv.getDiemth()+"");
				diemgk.setText(sv.getDiemgk()+"");
				diemck.setText(sv.getDiemck()+"");
				//diemtb.setText(sv.getDiemtb()+"");
	*/
        this.mssv.setText(model.getValueAt(tbSinhVien.getSelectedRow(), 0).toString());
        this.hotensv.setText(model.getValueAt(tbSinhVien.getSelectedRow(), 1).toString());
        this.diemqt.setText(model.getValueAt(tbSinhVien.getSelectedRow(), 2).toString());
        this.diemth.setText(model.getValueAt(tbSinhVien.getSelectedRow(), 3).toString());
        this.diemgk.setText(model.getValueAt(tbSinhVien.getSelectedRow(), 4).toString());
        this.diemck.setText(model.getValueAt(tbSinhVien.getSelectedRow(), 5).toString());
			
    }//GEN-LAST:event_tbSinhVienMouseClicked

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbSinhVien.getModel();
                sinhVienService =new SinhVienService();
                sv = new DiemHocTap();
                sv.setMssv(mssv.getText());
                sv.setMalopGD(layMaLop());
                if(sinhVienService.xoaDiemSinhVien(sv)){
                    JOptionPane.showMessageDialog(null, "Xóa thành công");
                    model.removeRow(tbSinhVien.getSelectedRow());
                }else{
                    JOptionPane.showMessageDialog(null, "Xóa thất bại");
                }
                
                //hienThiDanhSachSVLenBangDiem();
                
                
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbSinhVien.getModel();
        
        QLDSVService a=new QLDSVService();
        a.AddDIEMTB(tbSinhVien.getValueAt(tbSinhVien.getSelectedRow(), 0).toString(), a.hienThiDiemTrungBinhChung(tbSinhVien.getValueAt(tbSinhVien.getSelectedRow(), 0).toString()), a.hienThiTongTinChi(tbSinhVien.getValueAt(tbSinhVien.getSelectedRow(), 0).toString()));
            
            sinhVienService =new SinhVienService();
				float qt =Float.parseFloat(diemqt.getText());
				float th =Float.parseFloat(diemth.getText());
				float gk =Float.parseFloat(diemgk.getText());
				float ck =Float.parseFloat(diemck.getText());
				float tb =((Float.parseFloat(diemqt.getText())*1+ Float.parseFloat(diemth.getText())*2+ Float.parseFloat(diemgk.getText())*2+
						Float.parseFloat(diemck.getText())*5)/10);
                                sv = new DiemHocTap(); 
				sv.setMssv( mssv.getText());
				sv.setMalopGD(layMaLop());
				sv.setDiemqt(qt);
				sv.setDiemth(th);
				sv.setDiemgk(gk);
				sv.setDiemck(ck);
				sv.setDiemtb(tb);
				//dsSV.add(sv);
				
				int check=sinhVienService.capNhatDiemSinhVien(sv);
				if (check>0) 
					{
                                            JOptionPane.showMessageDialog(null, "Cập nhật thành công");
                                            model.setValueAt(mssv.getText(), tbSinhVien.getSelectedRow(), 0);
                                            model.setValueAt(hotensv.getText(), tbSinhVien.getSelectedRow(), 1);
                                            model.setValueAt(diemqt.getText(), tbSinhVien.getSelectedRow(), 2);
                                            model.setValueAt(diemth.getText(), tbSinhVien.getSelectedRow(), 3);
                                            model.setValueAt(diemgk.getText(), tbSinhVien.getSelectedRow(), 4);
                                            model.setValueAt(diemck.getText(), tbSinhVien.getSelectedRow(), 5);
                                            //hienThiDanhSachSVLenBangDiem();
					}
			
    }//GEN-LAST:event_btUpdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    protected void hienThiDanhSachSVLenBangDiem() {
		
		
		dtmSinhVien= (DefaultTableModel) tbSinhVien.getModel();
                dtmSinhVien.setRowCount(0);
		for(DiemHocTap sv:dsSV)
		{
			Vector<Object>vec=new Vector<Object>();
			vec.add(sv.getMssv());
			vec.add(sv.getTensv());
			vec.add(sv.getDiemqt());
			vec.add(sv.getDiemth());
			vec.add(sv.getDiemgk());
			vec.add(sv.getDiemck());
			vec.add(sv.getDiemtb());
			//vec.add(sv.getMalopGD());
			
			dtmSinhVien.addRow(vec);
		}
	//	dtmSinhVien.fireTableDataChanged();
		
		
	}

        public String layMaLop()
	{
		DefaultMutableTreeNode treeNode=(DefaultMutableTreeNode) treeDSLop.getLastSelectedPathComponent();
		if(treeNode==null) return null;
		if(treeNode.getLevel()==0) return null;
		if(sinhVienService==null) 
			{
			sinhVienService= new SinhVienService();
			}
		lop=(Lop) treeNode.getUserObject();
		return lop.getMaLop();
		
	}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhSachLopUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhSachLopUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhSachLopUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhSachLopUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DanhSachLopUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btUpdate;
    private javax.swing.JTextField diemck;
    private javax.swing.JTextField diemgk;
    private javax.swing.JTextField diemqt;
    private javax.swing.JTextField diemth;
    private javax.swing.JTextField hotensv;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField mssv;
    private javax.swing.JTable tbSinhVien;
    private javax.swing.JTree treeDSLop;
    // End of variables declaration//GEN-END:variables
}