/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Design;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.ScrollPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.BoxLayout;
import javax.swing.DefaultBoundedRangeModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

import Class.SinhVien;
/**
 *
 * @author hcshl
 */
public class MainSV extends javax.swing.JFrame {

    /**
     * Creates new form SinhVien
     */
    Connection conn;
    public MainSV() {
        initComponents();
        setLocation(0, 20);
        txtTenTK.setText(DangNhapUI.setLayTaiKhoan());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Nut_XemTTSV = new javax.swing.JButton();
        Nut_KQHT = new javax.swing.JButton();
        Nut_DKHP = new javax.swing.JButton();
        Nut_DoiMK = new javax.swing.JButton();
        NutThoat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenTK = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý điểm sinh viên");

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        Nut_XemTTSV.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Nut_XemTTSV.setText("Xem thông tin sinh viên");
        Nut_XemTTSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nut_XemTTSVActionPerformed(evt);
            }
        });
        jPanel1.add(Nut_XemTTSV);

        Nut_KQHT.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Nut_KQHT.setText("Kết quả học tập");
        Nut_KQHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nut_KQHTActionPerformed(evt);
            }
        });
        jPanel1.add(Nut_KQHT);

        Nut_DKHP.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Nut_DKHP.setText("Đăng ký học phần");
        Nut_DKHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nut_DKHPActionPerformed(evt);
            }
        });
        jPanel1.add(Nut_DKHP);

        Nut_DoiMK.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Nut_DoiMK.setText("Đổi mật khẩu");
        Nut_DoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nut_DoiMKActionPerformed(evt);
            }
        });
        jPanel1.add(Nut_DoiMK);

        NutThoat.setBackground(new java.awt.Color(255, 0, 51));
        NutThoat.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        NutThoat.setText("Đăng xuất");
        NutThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NutThoatActionPerformed(evt);
            }
        });
        jPanel1.add(NutThoat);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/UMS0-300x298.png"))); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tài khoản:");

        txtTenTK.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenTK, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ketNoiOracle() {
		try {
			Class.forName("oracle.jdbc.driver.OracleDriver");
			String strConn="jdbc:oracle:thin:@ThaoThao:1522/orcl";
			conn=DriverManager.getConnection(strConn, "THAO", "1234");
			//CallableStaiment excute procedure
		}
		catch(Exception ex)
		{
			ex.printStackTrace();
		}
	}
    
    private void Nut_XemTTSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nut_XemTTSVActionPerformed
        // TODO add your handling code here:    
	XemTTSinhVien A = new XemTTSinhVien();
        A.setVisible(true);

    }//GEN-LAST:event_Nut_XemTTSVActionPerformed

    private void Nut_KQHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nut_KQHTActionPerformed
        // TODO add your handling code here:
        QLDSVXemDiem A = new QLDSVXemDiem();
        A.setVisible(true);
        
    }//GEN-LAST:event_Nut_KQHTActionPerformed

    private void NutThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NutThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DangNhapUI A = new DangNhapUI();
        A.setVisible(true);
    }//GEN-LAST:event_NutThoatActionPerformed

    private void Nut_DoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nut_DoiMKActionPerformed
        // TODO add your handling code here:
        DoiMatKhau A= new DoiMatKhau();
        A.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Nut_DoiMKActionPerformed

    private void Nut_DKHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nut_DKHPActionPerformed
        // TODO add your handling code here:
        DangKyHocPhan A = new DangKyHocPhan();
        A.setVisible(true);
    }//GEN-LAST:event_Nut_DKHPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NutThoat;
    private javax.swing.JButton Nut_DKHP;
    private javax.swing.JButton Nut_DoiMK;
    private javax.swing.JButton Nut_KQHT;
    private javax.swing.JButton Nut_XemTTSV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtTenTK;
    // End of variables declaration//GEN-END:variables

    private void hienThiBangDiem(String setLayTaiKhoan) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}