/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Design;
import Service.QLDSVService;
import java.lang.*;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author hcshl
 */
public class QLDSVXemDiem extends javax.swing.JFrame {

    /**
     * Creates new form XemTTSinhVien
     */
       
        //DefaultTableModel dbtBangDiem;
        public QLDSVXemDiem() {
        initComponents();  
        setLocation(100, 100);
        ketNoiOracle();
        hienThiBangDiem(DangNhapUI.setLayTaiKhoan());
        hienthiDTB();
        hienthiTTC();
//        QLDSV.AddDIEMTB(DangNhapUI.setLayTaiKhoan(), QLDSV.hienThiDiemTrungBinhChung(DangNhapUI.setLayTaiKhoan()),
//                QLDSV.hienThiTongTinChi(DangNhapUI.setLayTaiKhoan()));
        } 
        
        
        Connection conn;
        public void ketNoiOracle() {
		try {
			Class.forName("oracle.jdbc.driver.OracleDriver");
			String strConn = "jdbc:oracle:thin:@localhost:1521/orcl";
			conn=DriverManager.getConnection(strConn, "HCS", "son123");			
		}
		catch(Exception ex)
		{
			ex.printStackTrace();
		}
	}
        QLDSVService QLDSV=new QLDSVService();
        
        private void hienthiDTB()
        {
            
            float A=QLDSV.hienThiDiemTrungBinhChung(DangNhapUI.setLayTaiKhoan());
            txtDiem.setText(String.valueOf(A));
        }
        
        private void hienthiTTC()
        {
            
            int A=QLDSV.hienThiTongTinChi(DangNhapUI.setLayTaiKhoan());
            txtTinhChi.setText(String.valueOf(A));
        }

//        private void hienThiDiemTrungBinhChung(String mssv) {
//		try {
//			String sql="{call SP_TINHDIEMTBHOCKY(?, ?)}";
//			CallableStatement call=conn.prepareCall(sql);
//			call.setString(1, mssv);
//			call.registerOutParameter(2, java.sql.Types.FLOAT);
//			call.executeQuery();
//			float a=call.getFloat(2);
//			txtDiem.setText(String.valueOf(a));
//			System.out.println(a);
//		}
//		catch(Exception ex)
//		{
//			ex.printStackTrace();
//		}
		
	
//	private void hienThiTongTinChi(String mssv) {
//		try {
//			String sql="{call SP_TOngSoTinChi(?, ?)}";
//			                 CallableStatement call=conn.prepareCall(sql);
//			call.setString(1, mssv);
//			call.registerOutParameter(2, java.sql.Types.INTEGER);
//			call.executeQuery();
//			int a=call.getInt(2);
//			txtTinhChi.setText(String.valueOf(a));
//			System.out.println(a);
//		}
//		catch(Exception ex)
//		{
//			ex.printStackTrace();
//		}
//		
//	}
        
private void hienThiBangDiem(String Mssv) {
                DefaultTableModel model = (DefaultTableModel) tbBangDiem.getModel();

	try {
		String sql ="select KETQUA.MAMH,MONHOC.TENMH,DIEMQT,DIEMGK,DIEMTH,DIEMCK,DIEMTB,DIEMCHU from KETQUA, MONHOC where MSSV=? and KETQUA.MAMH=MONHOC.MAMH";			
		PreparedStatement presta = conn.prepareStatement(sql);
		presta.setString(1, Mssv);
		ResultSet resul = presta.executeQuery();
                model.setRowCount(0);
                
		while(resul.next())
		{
			Object arrXemDiem[]= {                          
                                        resul.getString("MAMH"),
					resul.getString("TENMH"), resul.getString("DIEMQT"),
					resul.getString("DIEMGK"), resul.getString("DIEMTH"), 
					resul.getString("DIEMCK"), resul.getString("DIEMTB"), resul.getString("DIEMCHU")};
                        model.addRow(arrXemDiem);
                        
		}
		
            }
        catch(Exception ex)
		{
                        ex.printStackTrace();                        
		}
        try{
            String sql1="select TENSV from SINHVIEN where MSSV=?";
            PreparedStatement p = conn.prepareStatement(sql1);
            p.setString(1, Mssv);
            ResultSet rs = p.executeQuery();
            if(rs.next())
            {
                txt_KQHT_HOTEN.setText(rs.getString("TENSV"));
                txt_KQHT_MSSV.setText(Mssv);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBangDiem = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btPhucKhao = new javax.swing.JButton();
        NutQuaylai = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_KQHT_HOTEN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_KQHT_MSSV = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTinhChi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDiem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý điểm sinh viên");

        tbBangDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã môn học", "Tên môn học", "Điểm quá trình", "Điểm thực hành", "Điểm giữa kỳ", "Điểm cuối kỳ", "Điểm TBM", "Điểm chữ"
            }
        ));
        jScrollPane1.setViewportView(tbBangDiem);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1156, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 33)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KẾT QUẢ HỌC TẬP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setLayout(new java.awt.GridBagLayout());

        btPhucKhao.setText("Phúc khảo");
        btPhucKhao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPhucKhaoActionPerformed(evt);
            }
        });
        jPanel4.add(btPhucKhao, new java.awt.GridBagConstraints());

        NutQuaylai.setText("Quay Lại");
        NutQuaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NutQuaylaiActionPerformed(evt);
            }
        });
        jPanel4.add(NutQuaylai, new java.awt.GridBagConstraints());

        jPanel3.setLayout(new java.awt.GridLayout(1, 4));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Họ tên:");
        jPanel3.add(jLabel2);

        txt_KQHT_HOTEN.setEditable(false);
        jPanel3.add(txt_KQHT_HOTEN);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MSSV:");
        jPanel3.add(jLabel3);

        txt_KQHT_MSSV.setEditable(false);
        jPanel3.add(txt_KQHT_MSSV);

        jPanel5.setLayout(new java.awt.GridLayout(1, 4));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tín chỉ tích lũy:");
        jPanel5.add(jLabel4);

        txtTinhChi.setEditable(false);
        jPanel5.add(txtTinhChi);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Điểm trung bình chung:");
        jPanel5.add(jLabel5);

        txtDiem.setEditable(false);
        jPanel5.add(txtDiem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NutQuaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NutQuaylaiActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_NutQuaylaiActionPerformed

    private void btPhucKhaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPhucKhaoActionPerformed
        // TODO add your handling code here:
        PhucKhaoDiem pk = new PhucKhaoDiem();
        pk.setVisible(true);
    }//GEN-LAST:event_btPhucKhaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDSVXemDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDSVXemDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDSVXemDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDSVXemDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLDSVXemDiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NutQuaylai;
    private javax.swing.JButton btPhucKhao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbBangDiem;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtTinhChi;
    private javax.swing.JTextField txt_KQHT_HOTEN;
    private javax.swing.JTextField txt_KQHT_MSSV;
    // End of variables declaration//GEN-END:variables
}