/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Design;
import Class.SinhVien;
import Service.QLSVService;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import org.w3c.dom.Document;
/**
 *
 * @author hcshl
 */
public class QLSV extends javax.swing.JFrame {



    /**
     * Creates new form QLSV
     */
    public QLSV() {
        initComponents();
        setLocation(80, 10);
        ketNoiOracle();
    }
        QLSVService qlservice = new QLSVService();
        Connection conn;
    public void ketNoiOracle(){
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            String strConn = "jdbc:oracle:thin:@localhost:1521/orcl";
            conn=DriverManager.getConnection(strConn, "HCS", "son123");
        }catch (Exception ex){
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BangSV = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMSSV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNgaysinh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGioitinh = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtDiachi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMalop = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        NutAdd = new javax.swing.JButton();
        NutReset = new javax.swing.JButton();
        NutDelete = new javax.swing.JButton();
        NutFind = new javax.swing.JButton();
        NutList = new javax.swing.JButton();
        NutUpdate = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        NutExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý điểm sinh viên");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 33)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ SINH VIÊN");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1107, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        BangSV.setAutoCreateRowSorter(true);
        BangSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MSSV", "Họ tên", "Ngày sinh", "Giới tính", "Nơi sinh", "Mã lớp"
            }
        ));
        BangSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BangSVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BangSV);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jPanel4.setLayout(new java.awt.GridLayout(6, 2));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MSSV:");
        jPanel4.add(jLabel3);
        jPanel4.add(txtMSSV);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Họ và tên:");
        jPanel4.add(jLabel4);
        jPanel4.add(txtTen);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ngày sinh:");
        jPanel4.add(jLabel5);
        jPanel4.add(txtNgaysinh);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Giới tính:");
        jPanel4.add(jLabel6);

        txtGioitinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nu" }));
        jPanel4.add(txtGioitinh);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nơi sinh:");
        jPanel4.add(jLabel7);
        jPanel4.add(txtDiachi);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Mã lớp:");
        jPanel4.add(jLabel8);
        jPanel4.add(txtMalop);

        NutAdd.setText("Thêm");
        NutAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NutAddActionPerformed(evt);
            }
        });

        NutReset.setText("Nhập lại");
        NutReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NutResetActionPerformed(evt);
            }
        });

        NutDelete.setText("Xóa");
        NutDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NutDeleteActionPerformed(evt);
            }
        });

        NutFind.setText("Tìm sinh viên");
        NutFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NutFindActionPerformed(evt);
            }
        });

        NutList.setText("Danh sách sinh viên");
        NutList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NutListActionPerformed(evt);
            }
        });

        NutUpdate.setText("Sửa");
        NutUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NutUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(NutAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(NutReset)
                        .addGap(51, 51, 51))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(NutFind)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(NutList)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(NutUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(NutDelete)
                        .addGap(43, 43, 43))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NutAdd)
                    .addComponent(NutReset)
                    .addComponent(NutUpdate)
                    .addComponent(NutDelete))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NutList)
                    .addComponent(NutFind))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        NutExit.setBackground(new java.awt.Color(255, 51, 51));
        NutExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NutExit.setText("Thoát");
        NutExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NutExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NutExit, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NutExit, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NutResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NutResetActionPerformed
        // TODO add your handling code here:
        this.txtMSSV.setText(null);
        this.txtTen.setText(null);
        this.txtNgaysinh.setText(null);
        this.txtDiachi.setText(null);
        this.txtMalop.setText(null);
    }//GEN-LAST:event_NutResetActionPerformed
    private void NutAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NutAddActionPerformed
        // TODO add your handling code here:
        if(txtMSSV.getText().equals("")||txtTen.getText().equals("")||txtNgaysinh.getText().equals("")||
                txtDiachi.getText().equals("")||txtMalop.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập hết các trường!!!");
        }
        else {
            
              if(qlservice.xetMaLop(txtMalop.getText())==false){
                  JOptionPane.showMessageDialog(null, "Không tồn tại mã lớp tương ứng");
                  return;
              }
              
                
                
            
            if(txtMSSV.getText().length()!=8) {
            JOptionPane.showMessageDialog(this, "MSSV phải có 8 chữ số");
            
        }
            
            else {
                
            DefaultTableModel model = (DefaultTableModel) BangSV.getModel();
            
            if(qlservice.ThemDL(txtMSSV.getText(), txtTen.getText(), txtNgaysinh.getText(),
                    txtGioitinh.getSelectedItem().toString(), txtDiachi.getText(), txtMalop.getText())==true)
            {
                JOptionPane.showMessageDialog(null, "Thêm dữ liệu thành công");
                model.addRow(new Object[]{txtMSSV.getText(),txtTen.getText(),txtNgaysinh.getText(),
                                txtGioitinh.getSelectedItem(),txtDiachi.getText(),txtMalop.getText()});
            }else{
                JOptionPane.showMessageDialog(null, "Thêm dữ liệu không thành công");
            }
          

                }
        }
    }//GEN-LAST:event_NutAddActionPerformed

    private void NutExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NutExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_NutExitActionPerformed

    
    
    private void NutUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NutUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) BangSV.getModel();
        if(BangSV.getSelectedRow()==-1)
        {
            if(BangSV.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Không có trường nào trong bảng");
                }else{
                JOptionPane.showMessageDialog(this, "Bạn phải chọn 1 sinh viên");
            }
        }else{
            
            //update Oracle
            if(txtMSSV.getText().equals("")||txtTen.getText().equals("")||txtNgaysinh.getText().equals("")||
                txtDiachi.getText().equals("")||txtMalop.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập hết các trường!!!");
        }
        else {
                if(qlservice.xetMaLop(txtMalop.getText())==false){
                  JOptionPane.showMessageDialog(null, "Không tồn tại mã lớp tương ứng");
                  return;}
                
            
            if(txtMSSV.getText().length()!=8) {
            JOptionPane.showMessageDialog(this, "MSSV phải có 8 chữ số");
        }
        else{
            
            
            String MSSVX = model.getValueAt(BangSV.getSelectedRow(), 0).toString();
            
            if(qlservice.SuaDL(MSSVX, txtTen.getText(), txtNgaysinh.getText(), txtGioitinh.getSelectedItem().toString(),
                    txtDiachi.getText(), txtMalop.getText())==true)
            {
                JOptionPane.showMessageDialog(this, "Sửa dữ liệu thành công");   
                model.setValueAt(txtMSSV.getText(), BangSV.getSelectedRow(), 0);
                model.setValueAt(txtTen.getText(), BangSV.getSelectedRow(), 1);
                model.setValueAt(txtNgaysinh.getText(), BangSV.getSelectedRow(), 2);
                model.setValueAt(txtGioitinh.getSelectedItem().toString(), BangSV.getSelectedRow(), 3);
                model.setValueAt(txtDiachi.getText(), BangSV.getSelectedRow(), 4);
                model.setValueAt(txtMalop.getText(), BangSV.getSelectedRow(), 5);
            }else {
                JOptionPane.showMessageDialog(this, "Sửa dữ liệu không thành công");
            }
            }
            } 
        }
    }//GEN-LAST:event_NutUpdateActionPerformed

    
    
    private void BangSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BangSVMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) BangSV.getModel();
        this.txtMSSV.setText(model.getValueAt(BangSV.getSelectedRow(), 0).toString());
        this.txtTen.setText(model.getValueAt(BangSV.getSelectedRow(), 1).toString());
        this.txtNgaysinh.setText(model.getValueAt(BangSV.getSelectedRow(), 2).toString());
        this.txtGioitinh.setSelectedItem(model.getValueAt(BangSV.getSelectedRow(), 3).toString());
        this.txtDiachi.setText(model.getValueAt(BangSV.getSelectedRow(), 4).toString());
        this.txtMalop.setText(model.getValueAt(BangSV.getSelectedRow(), 5).toString());
        
    }//GEN-LAST:event_BangSVMouseClicked

    private void NutDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NutDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) BangSV.getModel();
        if(BangSV.getSelectedRow()==-1)
        {
            if(BangSV.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Không có trường nào trong bảng");
                }else{
                JOptionPane.showMessageDialog(this, "Bạn phải chọn 1 sinh viên");
            }
        }else{
            //Delete Oracle
            int click = JOptionPane.showConfirmDialog(this, "Xóa sinh viên?","Question",JOptionPane.YES_NO_OPTION);
            if(click==JOptionPane.YES_OPTION)
            {
            String MSSVX = model.getValueAt(BangSV.getSelectedRow(), 0).toString();
            
            if(qlservice.XoaDL(MSSVX)==true)
            {
                JOptionPane.showMessageDialog(this, "Xóa dữ liệu thành công");
                    model.removeRow(BangSV.getSelectedRow());
                    this.txtMSSV.setText(null);
                    this.txtTen.setText(null);
                    this.txtNgaysinh.setText(null);
                    this.txtDiachi.setText(null);
                    this.txtMalop.setText(null);    
            }else{
                JOptionPane.showMessageDialog(this, "Xóa dữ liệu không thành công");
            }
        }else{
                return;
            }
    } 

    }//GEN-LAST:event_NutDeleteActionPerformed

    private void NutFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NutFindActionPerformed
        // TODO add your handling code here:
        String A = "";
        A = JOptionPane.showInputDialog("Nhập MSSV của sinh viên cần tìm: ");
        
        DefaultTableModel model = (DefaultTableModel) BangSV.getModel();
        
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        model.setRowCount(0);
        
        if(qlservice.FindDL(A)==null){
            JOptionPane.showMessageDialog(null, "Không tìm thấy sinh viên!");
        }else{
            model.addRow(qlservice.FindDL(A));
        }
    }//GEN-LAST:event_NutFindActionPerformed

    private void NutListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NutListActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) BangSV.getModel();
        int rowCounts = model.getRowCount();
        for(int i = rowCounts - 1; i >= 0 ;i--){
            model.removeRow(i);
        }
        model.setRowCount(0);
        
        ArrayList<SinhVien> arrListSV=new ArrayList<SinhVien>();
        arrListSV=qlservice.ListDL();
        for(SinhVien a: arrListSV)
        {
            Vector<Object> vec =new Vector<Object>();
            vec.add(a.getMssv());
            vec.add(a.getTenSV());
            vec.add(a.getNgaysinh());
            vec.add(a.getGioiTinh());
            vec.add(a.getNoisinh());
            vec.add(a.getMaLop());
            model.addRow(vec);
            
        }
        
    }//GEN-LAST:event_NutListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BangSV;
    private javax.swing.JButton NutAdd;
    private javax.swing.JButton NutDelete;
    private javax.swing.JButton NutExit;
    private javax.swing.JButton NutFind;
    private javax.swing.JButton NutList;
    private javax.swing.JButton NutReset;
    private javax.swing.JButton NutUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JComboBox txtGioitinh;
    private javax.swing.JTextField txtMSSV;
    private javax.swing.JTextField txtMalop;
    private javax.swing.JTextField txtNgaysinh;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}