/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Design;

import Service.QLGVService;
import Service.QLSVService;

/**
 *
 * @author hcshl
 */
public class XemTTGiangVien extends javax.swing.JFrame {

    /**
     * Creates new form XemTTGiangVien
     */
        QLGVService A = new QLGVService(); 
    public XemTTGiangVien() {
        initComponents();
        setLocation(100, 100);
        hienThiThongTinGV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_TT_MAGV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_TT_HoTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_TT_HocVi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_TT_GioiTinh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_TT_NgaySinh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_TT_NgayVL = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_TT_HeSoLuong = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_TT_MucLuong = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý điểm sinh viên");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("THÔNG TIN GIẢNG VIÊN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel2.setLayout(new java.awt.GridLayout(8, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MAGV:");
        jPanel2.add(jLabel1);

        txt_TT_MAGV.setEditable(false);
        txt_TT_MAGV.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel2.add(txt_TT_MAGV);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Họ tên:");
        jPanel2.add(jLabel2);

        txt_TT_HoTen.setEditable(false);
        jPanel2.add(txt_TT_HoTen);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Học vị:");
        jPanel2.add(jLabel5);

        txt_TT_HocVi.setEditable(false);
        jPanel2.add(txt_TT_HocVi);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Giới tính:");
        jPanel2.add(jLabel4);

        txt_TT_GioiTinh.setEditable(false);
        jPanel2.add(txt_TT_GioiTinh);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ngày sinh:");
        jPanel2.add(jLabel3);

        txt_TT_NgaySinh.setEditable(false);
        jPanel2.add(txt_TT_NgaySinh);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ngày vào làm:");
        jPanel2.add(jLabel6);

        txt_TT_NgayVL.setEditable(false);
        jPanel2.add(txt_TT_NgayVL);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Hệ số lương:");
        jPanel2.add(jLabel8);

        txt_TT_HeSoLuong.setEditable(false);
        jPanel2.add(txt_TT_HeSoLuong);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Mức lương:");
        jPanel2.add(jLabel9);

        txt_TT_MucLuong.setEditable(false);
        jPanel2.add(txt_TT_MucLuong);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        btback.setText("Quay lại");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });
        jPanel3.add(btback, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void hienThiThongTinGV(){
        txt_TT_MAGV.setText(A.AddTextField().getMaGV());
        txt_TT_HoTen.setText(A.AddTextField().getTenGV());
        txt_TT_GioiTinh.setText(A.AddTextField().getGioitinh());
        txt_TT_NgaySinh.setText(A.AddTextField().getNgaySinh());
        txt_TT_NgayVL.setText(A.AddTextField().getNgayVL());
        txt_TT_HocVi.setText(A.AddTextField().getHocVi());
        txt_TT_HeSoLuong.setText(A.AddTextField().getHeSoLuong());
        txt_TT_MucLuong.setText(A.AddTextField().getMucLuong());
        
    }
    
    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemTTGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemTTGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemTTGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemTTGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XemTTGiangVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt_TT_GioiTinh;
    private javax.swing.JTextField txt_TT_HeSoLuong;
    private javax.swing.JTextField txt_TT_HoTen;
    private javax.swing.JTextField txt_TT_HocVi;
    private javax.swing.JTextField txt_TT_MAGV;
    private javax.swing.JTextField txt_TT_MucLuong;
    private javax.swing.JTextField txt_TT_NgaySinh;
    private javax.swing.JTextField txt_TT_NgayVL;
    // End of variables declaration//GEN-END:variables
}